steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/data-engineering-class-423503/d-repo/myimage:v1', '.' ]
  # push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-central1-docker.pkg.dev/data-engineering-class-423503/d-repo/myimage:v1']
  # deploy to cloud run on GKE
- name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
  entrypoint: gcloud
  args: ['run', 'deploy', 'py-web-ui', '--image', 'us-central1-docker.pkg.dev/data-engineering-class-423503/d-repo/myimage:v1', '--region', 'us-central1', '--allow-unauthenticated']
options:
  logging: CLOUD_LOGGING_ONLY  
